import type { Metadata } from "next";
import { Inter, Oswald, Poppins } from "next/font/google";
import "./globals.css";
import Encabezado from "@/components/encabezado/Encabezado";

const oswald = Oswald({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${oswald.className}`}>
        <Encabezado />
        {children}
      </body>
    </html>
  );
}
