import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Encabezado from "@/components/encabezado/Encabezado";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link href="https://fonts.cdnfonts.com/css/coldiac-free" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Encabezado />
        {children}
      </body>
    </html>
  );
}
